### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by glensc**
use echo for messages; exit for exit code. also cosmetics to terminate messages with newline.

`exit(NUMBER);` is good for checking from (shell) scripts that the previous command failed.

### CODE REVIEW

**Comment by aik099** [comment]
I see build is failing, but not due your changes. Could you please submit another PR with travis ci config changes to enable openssl extension for PHP 5.3.3.

**Comment by glensc** [comment]
or put 5.3.3 to allow failures?

**Comment by aik099** [comment]
> or put 5.3.3 to allow failures?

Of course not, because all previous PHP 5.3.3 builds have passed. Probably Travis CI issue with missing extension, but if we can fix it ourselves, then it would be good too.

**Comment by glensc** [comment]
i updated only README.md, having this PR blocked due travis issues is silly.

**Comment by aik099** [comment]
I'm not saying that PR can't be merged due travis build fail due unrelated reason 😄 

I'm just suggesting to send PR (if you can) fixing travis build.

**Comment by glensc** [comment]
i came across again to this repository and wanted to submit the exact same PR. ugly!

**Comment by theofidry** [comment]
Thanks @glensc

**Pull request merged**
