### PR TITLE
Create .styleci.yml

### PR DESCRIPTION
**Pull request by padraic**
Add PSR-2 screening.

### CODE REVIEW

**Comment by theofidry** [comment]
@humbug/core wdyt of waiting for two approvals before merging and when the two are given anyone can merge?

**Comment by padraic** [comment]
@theofidry That sounds good here - I was going to bring up on a issue thread with a few other items, but let's see what the other guys think.

**Comment by pamil** [comment]
Sounds good! The only edge case happens when a core member opens a PR, shall we treat it as implicit approval or require two other core members to approve it?

**Comment by theofidry** [comment]
@pamil as a rule I would say no exception (for that case). However I'm also for being a minimal flexible: if the PR is relatively simple (e.g. merge a StyleCI fix) I would be ok with only one approval

**Comment by padraic** [comment]
I agree on keeping exceptions to simple cases - it may extend the time to getting stuff merged, but it also adds an additional layer of checking, and keeps everyone informed about what's going into the code ;).

**Pull request merged**
